sequenceDiagram
    participant Alix
    participant Bo
    participant Caro
    participant XMTP

    Alix->>XMTP: conversations.create_group(Bo, Caro)
    Bo->>XMTP: conversations.sync()
    Bo->>+XMTP: conversations.list()
    XMTP-->>-Bo: List of groups including new group
    Caro->>XMTP: conversations.sync()
    Caro->>+XMTP: conversations.list()
    XMTP-->>-Caro: List of groups including new group  