flowchart TD
    A[Inbox ID] --> B[Embedded wallet - Converse]
    A --> C[Embedded Wallet - Other Messaging App]
    A --> D[Portable wallet - Hot wallet]
    A --> E[Portable wallet - Cold wallet]
    A --> F[Burner wallet]
    B -->|ENS subdomain| G[vitalik.converse.xyz]
    D -. ENS .-> H[vitalik.eth]
    D -. Farcaster association .-> I[Embedded wallet - Farcaster]
    D -. Lens assocation.-> J[lens/vitalik]
    D -.Other protocol .-> K[Embedded wallet - other protocol]
    E -. Owns .-> L[Valuable NFTs]
    I -. ENS subdomain .-> M[vitalik.fcast.id]