sequenceDiagram
    participant Alix
    participant Bo
    participant Caro
    participant XMTP

    Note left of Alix: Send Message
    Alix->>XMTP: group.send("Hello, group!")
    Alix->>XMTP: group.sync()

    Note left of Alix: Receive Message
    Bo->>XMTP: group.sync()
    Bo->>XMTP: group.find_messages()
    XMTP-->>Bo: "Alix: Hello, group!"

    Caro->>XMTP: group.sync()
    Caro->>XMTP: group.find_messages()
    XMTP-->>Caro: "Alix: Hello, group!"