sequenceDiagram
    participant Amal
    participant Bola
    participant Caro
    participant XMTP

    Amal->>+XMTP: create_client(encryption_key, account_address)
    XMTP-->>-Amal: client
    Amal->>+XMTP: client.signature_request().signature_text()
    XMTP-->>-Amal: text to be signed for register_identity
    Amal->>XMTP: client.register_identity(signature_request)
    Bola->>+XMTP: create_client(encryption_key, account_address)
    XMTP-->>-Bola: client
    Bola->>+XMTP: client.signature_request().signature_text()
    XMTP-->>-Bola: text to be signed for register_identity
    Bola->>XMTP: client.register_identity(signature_request)
    Caro->>+XMTP: create_client(encryption_key, account_address)
    XMTP-->>-Caro: client
    Caro->>+XMTP: client.signature_request().signature_text()
    XMTP-->>-Caro: text to be signed for register_identity
    Caro->>XMTP: client.register_identity(signature_request)
    Amal->>XMTP: conversations.create_group(Bola, Caro)
    Bola->>XMTP: conversations.sync()
    Bola->>+XMTP: conversations.list()
    XMTP-->>-Bola: List of groups including new group
    Caro->>XMTP: conversations.sync()
    Caro->>+XMTP: conversations.list()
    XMTP-->>-Caro: List of groups including new group      