sequenceDiagram
    participant Alix
    participant Bo
    participant Caro
    participant XMTP

    Alix->>+XMTP: create_client(encryption_key, account_address)
    XMTP-->>-Alix: client
    Alix->>+XMTP: client.signature_request().signature_text()
    XMTP-->>-Alix: text to be signed for register_identity
    Alix->>XMTP: client.register_identity(signature_request)
    Bo->>+XMTP: create_client(encryption_key, account_address)
    XMTP-->>-Bo: client
    Bo->>+XMTP: client.signature_request().signature_text()
    XMTP-->>-Bo: text to be signed for register_identity
    Bo->>XMTP: client.register_identity(signature_request)
    Caro->>+XMTP: create_client(encryption_key, account_address)
    XMTP-->>-Caro: client
    Caro->>+XMTP: client.signature_request().signature_text()
    XMTP-->>-Caro: text to be signed for register_identity
    Caro->>XMTP: client.register_identity(signature_request)
    Alix->>XMTP: conversations.create_group(Bo, Caro)
    Bo->>XMTP: conversations.sync()
    Bo->>+XMTP: conversations.list()
    XMTP-->>-Bo: List of groups including new group
    Caro->>XMTP: conversations.sync()
    Caro->>+XMTP: conversations.list()
    XMTP-->>-Caro: List of groups including new group      