---
new_page_extension: md
auto_deploy: false
admin_path: "/blog/admin"
webhook_url:
sections:
- type: document
  path: blog/authors.yml
  label: Authors
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: static/blog/media
public_path: "/blog/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:-:month:-:day:-:filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
